### ISSUE TITLE
This field is not of message type

### ISSUE THREAD

**Issue by krussan** [krussan/protodb#8]
at se.qxx.protodb.Searcher.getColumnListForJoin(Searcher.java:165)
        at se.qxx.protodb.Searcher.getColumnListForJoin(Searcher.java:192)
        at se.qxx.protodb.Searcher.getColumnListForJoin(Searcher.java:192)
        at se.qxx.protodb.Searcher.getJoinQuery(Searcher.java:42)
        at se.qxx.protodb.Searcher.getJoinQuery(Searcher.java:21)
        at se.qxx.protodb.ProtoDB.search(ProtoDB.java:1301)
        at se.qxx.protodb.ProtoDB.search(ProtoDB.java:1291)

**Comment by krussan** [comment]
Probably caused by the field being an Enum
